name: Update RSS

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:       # Позволяет запуск вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          python scripts/generate_rss.py --playlist PLSiLlNvYaVdUVIuzS5wL_s8izfq24jPrw --output youtube_podcast_rss.xml

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add youtube_podcast_rss.xml
          git commit -m "update rss" || echo "No changes to commit"
          git push
