name: Update RSS

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:       # Позволяет запускать вручную из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@74d5c5681915a7e62c1a42986363960c0e2d9272

            - name: Set up Python
        uses: actions/setup-python@e2a63f4fc37c76197d4b7ca581efb5f22e9e03ab

        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          python scripts/generate_rss.py --playlist PLSiLlNvYaVdUVIuzS5wL_s8izfq24jPrw --output youtube_podcast_rss.xml

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add youtube_podcast_rss.xml || true
          if ! git diff --staged --quiet; then
            COMMIT_MESSAGE="Auto-update RSS: $(date -u +'%Y-%m-%d %H:%M:%S')"
            git commit -m "$COMMIT_MESSAGE"
            git push
          else
            echo "No changes to commit"
